"""change role model

Revision ID: 05ef0a3f477c
Revises: bbfb71f8c2fd
Create Date: 2018-03-07 11:16:45.944341

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '05ef0a3f477c'
down_revision = 'bbfb71f8c2fd'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'user', 'role', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    # ### end Alembic commands ###
