"""add timestamp to comment

Revision ID: 63e8960f563e
Revises: 77e689210fa0
Create Date: 2018-02-27 15:11:43.527643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63e8960f563e'
down_revision = '77e689210fa0'
branch_labels = ()
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'timestamp')
    # ### end Alembic commands ###
